# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "FlyingTerrier"
description:	       "Loty w inspirujące miejsca w atrakcyjnych cenach"
author:              "Flying Terrier"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
url: "https://flyingterrier.com"
github.url: "https://flyingterrier.com"